# Use the official Redis image as a base image
FROM redis:alpine

# Expose the default Redis port
EXPOSE 6379

# Optionally, you can copy a custom Redis configuration file into the container
COPY redis.conf /usr/local/etc/redis/redis.conf

# Start Redis server with the configuration file, or with the default configuration
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

# If no custom configuration, simply start Redis
#CMD ["redis-server"]